# Camera
BOARD_CAMERA_SENSORS := s5k4h5_8916 gc2355
TARGET_USE_VENDOR_CAMERA_EXT := true
USE_DEVICE_SPECIFIC_CAMERA := true


#TARGET_USES_AOSP := true
TARGET_USES_MEDIA_EXTENSIONS:= false
#BOARD_USES_AOSP_CAMERA := true
BOARD_QTI_CAMERA_32BIT_ONLY := true
TARGET_HAS_LEGACY_CAMERA_HAL1 := true
